name: "Github Action for Helm and Helmfile on EKS (with aws-iam-authenticator)"
description: "Authenticates on EKS clusters using aws-iam-authenticator and executes Helm (or Helmfile) commands. Can also be used with kubectl commands."
branding:
  icon: 'anchor'  
  color: 'blue'
inputs:
  command:
    description: "Your command (kubectl, helm or helmfile)"
    required: true
outputs:
  result:
    description: "Output returned by your Helm, Helmfile or kubectl command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}